"""Criando tabelas no banco

Revision ID: f5c625079f96
Revises: 
Create Date: 2024-03-13 09:28:47.906506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c625079f96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('impressora', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setores_id'), 'setores', ['id'], unique=False)
    op.create_index(op.f('ix_setores_impressora'), 'setores', ['impressora'], unique=False)
    op.create_index(op.f('ix_setores_nome'), 'setores', ['nome'], unique=False)
    op.create_index(op.f('ix_setores_sigla'), 'setores', ['sigla'], unique=False)
    op.create_table('impressoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade_impressoes', sa.Integer(), nullable=True),
    sa.Column('id_setor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_setor'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impressoes_id'), 'impressoes', ['id'], unique=False)
    op.create_index(op.f('ix_impressoes_quantidade_impressoes'), 'impressoes', ['quantidade_impressoes'], unique=False)
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('quantidade_resmas', sa.Integer(), nullable=True),
    sa.Column('id_setor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_setor'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_id'), 'solicitacoes', ['id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_matricula'), 'solicitacoes', ['matricula'], unique=False)
    op.create_index(op.f('ix_solicitacoes_nome'), 'solicitacoes', ['nome'], unique=False)
    op.create_index(op.f('ix_solicitacoes_quantidade_resmas'), 'solicitacoes', ['quantidade_resmas'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacoes_quantidade_resmas'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_nome'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_matricula'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_id'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    op.drop_index(op.f('ix_impressoes_quantidade_impressoes'), table_name='impressoes')
    op.drop_index(op.f('ix_impressoes_id'), table_name='impressoes')
    op.drop_table('impressoes')
    op.drop_index(op.f('ix_setores_sigla'), table_name='setores')
    op.drop_index(op.f('ix_setores_nome'), table_name='setores')
    op.drop_index(op.f('ix_setores_impressora'), table_name='setores')
    op.drop_index(op.f('ix_setores_id'), table_name='setores')
    op.drop_table('setores')
    # ### end Alembic commands ###
